// src/screens/ReclamoListScreen.js
import React from 'react';
import { View, FlatList, StyleSheet } from 'react-native';
import { List, Title } from 'react-native-paper';
import Navbar from '../components/Navbar';

const ReclamoListScreen = ({ navigation }) => {
    // Datos de prueba
    const reclamos = [
        {
            id: 1,
            numero_calle: 123,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Falta de iluminación en la calle',
            fecha_fin_estimada: new Date('2023-10-15'),
            fecha_creacion: new Date('2023-10-01'),
            motivo: 'Iluminación',
            localidad: 'Buenos Aires',
            calle: 'Calle Falsa',
            ciudadano: 'Juan Pérez',
            prioridad_reclamo: 'Alta',
            origen_reclamo: 'App Móvil',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'jperez',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        {
            id: 2,
            numero_calle: 456,
            latitud: -34.6037,
            longitud: -58.3816,
            comentario: 'Bache en la calzada',
            fecha_fin_estimada: new Date('2023-10-20'),
            fecha_creacion: new Date('2023-10-02'),
            motivo: 'Bacheo',
            localidad: 'Buenos Aires',
            calle: 'Avenida Siempre Viva',
            ciudadano: 'María García',
            prioridad_reclamo: 'Media',
            origen_reclamo: 'Web',
            calificacion_reclamo: 'Pendiente',
            usuario_creador: 'mgarcia',
            reclamo_unificado: null,
        },
        // Puedes agregar más reclamos de prueba aquí
    ];

    const renderItem = ({ item }) => (
        <List.Item
            title={`Reclamo #${item.id}`}
            description={`Fecha: ${new Date(item.fecha_creacion).toLocaleDateString()}` || 'No disponible'}
            left={(props) => <List.Icon {...props} icon="file-document" />}
            onPress={() => {
                // Navegar a la pantalla de detalle pasando el reclamo seleccionado
                navigation.navigate('ReclamoDetail', { reclamo: item });
            }}
            //para hacer a posterior enviar el id del reclamo
            /* onPress={() => {
                navigation.navigate('ReclamoDetail', { reclamoId: item.id });
              }} */
        />
    );

    return (
        <View style={styles.container}>
            <Navbar title="Inicio" />
            <FlatList
                data={reclamos}
                keyExtractor={(item) => item.id.toString()}
                renderItem={renderItem}
                contentContainerStyle={styles.container}
            />
        </View>
    );
};

export default ReclamoListScreen;

const styles = StyleSheet.create({
    container: {
        padding: 10,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
});
